In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.9.1'

In [8]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
scaler.ndim

0

In [10]:
vector = tf.constant([10, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [11]:
vector.ndim

1

In [12]:
matrix = tf.constant([
    [1,2],
    [3,4]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [13]:
matrix.ndim

2

In [14]:
matrix = tf.constant([
    [1.,2.],
    [3.,4.],
    [5.,6.]
],
dtype=tf.float16)
matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [16]:
matrix = tf.constant(
    [[[1.,2.],
    [3.,4.],
    [5.,6.]],

    [[1.,2.],
    [3.,4.],
    [5.,6.]],

    [[1.,2.],
    [3.,4.],
    [5.,6.]]],
dtype=tf.float16)
matrix

<tf.Tensor: shape=(3, 3, 2), dtype=float16, numpy=
array([[[1., 2.],
        [3., 4.],
        [5., 6.]],

       [[1., 2.],
        [3., 4.],
        [5., 6.]],

       [[1., 2.],
        [3., 4.],
        [5., 6.]]], dtype=float16)>

In [17]:
matrix.ndim

3

In [26]:
v = tf.Variable(
    [10,7]
)
c = tf.constant(
    [10,7]
)
v, c

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [27]:
v[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [28]:
v

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

tf.variable is mutable

tf.constant is immutable

## Random Tensor

In [30]:
tf.random.uniform(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.8088157 , 0.508307  ],
       [0.6434394 , 0.19937313]], dtype=float32)>

In [31]:
tf.random.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.26686352, 0.92856604],
       [0.19417116, 0.58083004]], dtype=float32)>

### Shuffling

In [73]:
a = tf.constant(
    [[1,2],
    [3,4],
    [4,5],
    [6,7],
    [8,9]]
)

In [91]:
tf.random.set_seed(1)  # global level seed
tf.random.shuffle(a, seed=10)  # operation level seed

# when both seeds are same shuffling will be the output 

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[6, 7],
       [8, 9],
       [1, 2],
       [4, 5],
       [3, 4]])>

In [90]:
tf.random.set_seed(10)
tf.random.shuffle(a, seed=10)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[6, 7],
       [4, 5],
       [1, 2],
       [8, 9],
       [3, 4]])>

In [ ]:
tf.constant()