In [40]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.9.1'

In [3]:
scaler = tf.constant(7)
print(scaler.ndim)
print(scaler)

0
tf.Tensor(7, shape=(), dtype=int32)


In [10]:
vector = tf.constant([10, 7])
print(vector.ndim)
print(vector)

1
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [7]:
matrix = tf.constant([
    [1,2,3],
    [3,4,5],
    [3,4,5]
])
print(matrix.ndim)
print(matrix)

2
tf.Tensor(
[[1 2 3]
 [3 4 5]
 [3 4 5]], shape=(3, 3), dtype=int32)


In [14]:
matrix = tf.constant([
    [1.,2.],
    [3.,4.],
    [5.,6.]
],
dtype=tf.float16)
matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [9]:
tensor1 = tf.constant(
    [[[1.,2.],
    [3.,4.],
    [5.,6.]],

    [[1.,2.],
    [3.,4.],
    [5.,6.]],

    [[1.,2.],
    [3.,4.],
    [5.,6.]]],
dtype=tf.float16)
print(tensor1.ndim)
tensor1

3


<tf.Tensor: shape=(3, 3, 2), dtype=float16, numpy=
array([[[1., 2.],
        [3., 4.],
        [5., 6.]],

       [[1., 2.],
        [3., 4.],
        [5., 6.]],

       [[1., 2.],
        [3., 4.],
        [5., 6.]]], dtype=float16)>

In [17]:
v = tf.Variable(
    [10,7]
)
c = tf.constant(
    [10,7]
)
v, c

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [18]:
v[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [19]:
v

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

tf.variable is mutable

tf.constant is immutable

## Random Tensor

In [29]:

rand1 = tf.random.Generator.from_seed(10)  # for reproducibility
rand1.uniform(shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.93598676, 0.6513264 , 0.31663585],
       [0.00111556, 0.9212191 , 0.3822806 ]], dtype=float32)>

In [30]:

rand1 = tf.random.Generator.from_seed(10)  # for reproducibility
rand1.uniform(shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.93598676, 0.6513264 , 0.31663585],
       [0.00111556, 0.9212191 , 0.3822806 ]], dtype=float32)>

In [31]:
tf.random.uniform(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.47720265, 0.33357763],
       [0.4960823 , 0.48351312]], dtype=float32)>

In [32]:
tf.random.normal(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.4789797 , -0.29240268],
       [ 0.07752764, -0.5062714 ]], dtype=float32)>

### Shuffling

In [34]:
a = tf.constant(
    [[1,2],
    [3,4],
    [4,5],
    [6,7],
    [8,9]]
)

In [39]:
tf.random.set_seed(1)  # global level seed
tf.random.shuffle(a, seed=10)  # operation level seed

# when both global and operational seeds are fixed,
# the shuffling output  will be the same

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[6, 7],
       [8, 9],
       [1, 2],
       [4, 5],
       [3, 4]])>

In [90]:
tf.random.set_seed(10)
tf.random.shuffle(a, seed=10)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[6, 7],
       [4, 5],
       [1, 2],
       [8, 9],
       [3, 4]])>

In [59]:
# tf.random.set_seed(10)
tf.random.shuffle(a, seed=10)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [8, 9],
       [4, 5],
       [6, 7]])>

In [60]:
tf.zeros(shape=[3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [61]:
tf.ones(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

## Creating tensors from numpy array

In [64]:
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [69]:
tf.constant(a,shape=[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

## Getting information from tensors

In [70]:
print('Shape:',a.shape)
print('Dimension:',a.ndim)
print('Size:',tf.size(a))


Shape: (2, 3)
Dimension: 2
Size: tf.Tensor(6, shape=(), dtype=int32)


In [72]:
# slicing
a = tf.zeros(shape=[5,5])
a

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [74]:
a[:3,:3]

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [78]:
a = tf.constant(
    [[1,2,3],
    [4,5,6]]
)
a[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6])>

In [87]:
# adding new axis
b = a[:,:,tf.newaxis]
b

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

In [88]:
# adding new axis
b = a[:,tf.newaxis]
b

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]]])>

In [89]:
# adding new axis
b = a[tf.newaxis,:]
b

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]])>

In [96]:
# alternate
tf.expand_dims(a, axis=0)

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]])>

In [97]:
# alternate
tf.expand_dims(a, axis=1)

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]]])>

## Manipulating Tensors

In [98]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [99]:
a+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [100]:
a*2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [101]:
a-1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

In [102]:
tf.math.multiply(a,2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [103]:
tf.math.add(a,2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]])>

In [104]:
tf.math.subtract(a,2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-1,  0,  1],
       [ 2,  3,  4]])>

### Matrix Multiplication

In [110]:
a = tf.constant(
    [[7,10,4],
    [10,7,6],
    [2,6,9]]
)
b = tf.constant(
    [[5,6],
    [8,2],
    [7,9]]
)
print(a)
print(b)

tf.Tensor(
[[ 7 10  4]
 [10  7  6]
 [ 2  6  9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[5 6]
 [8 2]
 [7 9]], shape=(3, 2), dtype=int32)


In [111]:
tf.matmul(a,b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[143,  98],
       [148, 128],
       [121, 105]])>

In [116]:
b, tf.transpose(b), tf.reshape(b, shape=[2,3])

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 6],
        [8, 2],
        [7, 9]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 8, 7],
        [6, 2, 9]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[5, 6, 8],
        [2, 7, 9]])>)

In [119]:
# transpose flips the axes, rows become columns and viseversa
# reshape re-orders elements

In [121]:
tf.tensordot(a,b, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[143,  98],
       [148, 128],
       [121, 105]])>

In [124]:
tf.matmul(a,b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[143,  98],
       [148, 128],
       [121, 105]])>

In [132]:
a = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

b = tf.constant([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

In [133]:
tf.matmul(tf.transpose(a),b)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[54, 42, 30],
       [72, 57, 42],
       [90, 72, 54]])>

In [134]:
tf.matmul(a,tf.transpose(b))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 46,  28,  10],
       [118,  73,  28],
       [190, 118,  46]])>

### change dtype of tensors

In [145]:
a = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [146]:
tf.cast(a, dtype=tf.float16)

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

### Aggregating Tensors

In [147]:
# collective value

In [150]:
a = tf.constant([
    [1,-2,3],
    [-4,5,-6],
    [7,-8,9]
])
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1, -2,  3],
       [-4,  5, -6],
       [ 7, -8,  9]])>

In [151]:
# absolute type aggregation
tf.abs(a)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [152]:
# min
# max
# mean
# sum

In [163]:
a = tf.random.normal([10,5],2,2)
a

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-0.7628522 ,  1.4284546 ,  1.8382713 , -0.43870997,  1.7443647 ],
       [ 7.2479506 ,  1.1959742 , -1.0478489 ,  3.288359  ,  0.12766409],
       [ 2.4645238 ,  0.1862812 , -2.938806  ,  2.4259014 ,  0.8739903 ],
       [ 2.566231  ,  4.8552256 ,  0.9006542 ,  2.482572  ,  2.7306845 ],
       [-0.15775776, -2.9245486 ,  2.6628504 ,  0.31067967,  2.2968612 ],
       [-1.5952265 ,  4.2984004 ,  1.9333012 ,  3.4694698 ,  4.9936113 ],
       [-0.49191213,  4.355627  ,  2.500719  ,  3.6255026 ,  2.971458  ],
       [ 1.3313882 ,  0.666944  ,  4.901434  ,  3.044814  ,  3.1371906 ],
       [ 2.556534  ,  5.3344164 ,  1.4806266 ,  2.0479803 ,  0.41871023],
       [ 1.9491822 , -0.13512707, -1.6220429 ,  1.302237  ,  0.3607434 ]],
      dtype=float32)>

In [175]:
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.938806>

In [165]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=7.2479506>

In [166]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=1.723859>

In [167]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=float32, numpy=86.19295>

In [169]:
# variance # Standard Deviation 

In [171]:
tf.math.reduce_variance(a)

<tf.Tensor: shape=(), dtype=float32, numpy=4.3584623>

In [173]:
tf.math.reduce_std(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.087693>

### Positional min/max

In [188]:
a = tf.constant([
    [1,6,3],
    [2,5,8],
    [7,4,9]
])
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 6, 3],
       [2, 5, 8],
       [7, 4, 9]])>

#### If want values

In [192]:
tf.reduce_min(a,0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 3])>

In [193]:
tf.reduce_min(a,1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 4])>

#### If want indexs

In [194]:
tf.argmax(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 0, 2], dtype=int64)>

In [197]:
print(a)

tf.Tensor(
[[1 6 3]
 [2 5 8]
 [7 4 9]], shape=(3, 3), dtype=int32)


In [195]:
tf.argmax(a,1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 2], dtype=int64)>

### Sqeezing tensor

In [201]:
tf.random.set_seed(42)
a = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,50])
a.shape

TensorShape([1, 1, 1, 50])

In [203]:
tf.squeeze(a).shape

TensorShape([50])

## One-Hot Encoding

In [227]:
list1 = [0,5,2,3,4,0,2,4]  # these are considered as indices and not the actual unique values
list1

[0, 5, 2, 3, 4, 0, 2, 4]

In [229]:
tf.one_hot(list1, depth=6)

<tf.Tensor: shape=(8, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)>

#### Square, Square root, log operation

In [230]:
a = tf.range(10)
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [231]:
tf.square(a)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [234]:
tf.sqrt(tf.cast(a, dtype=tf.float32))  # methods requires float numbers

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [236]:
tf.math.log(tf.cast(a, dtype=tf.float32))  # methods requires float numbers

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

if np arrays converted into tensors dtype will be int64
if direct tensors are created dtype will be int32

In [239]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]